import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shivam',
      email: 'shivampatel@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'FMC',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'shiv',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
        name: 'Coragen',
        category: 'Insecticides',
        image: '/images/product-1.jpg',
        price: 800,
        brand: 'FMC',
        rating: 4.0,
        numReviews: 10,
        countInStock: 2,
        description: 'high quality product',
    },
    {
        name: 'Regent',
        category: 'Insecticides',
        image: '/images/product-2.jpg',
        price: 800,
        brand: 'BAYER',
        rating: 5.0,
        numReviews: 10,
        countInStock: 6,
        description: 'high quality product',
    },
    {
        name: 'Ampligo',
        category: 'Insecticides',
        image: '/images/product-3.jpg',
        price: 1600,
        brand: 'SYNGENTA',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
        description: 'high quality product',
    },
    {
        name: 'Benevia',
        category: 'Insecticides',
        image: '/images/product-4.jpg',
        price: 1400,
        brand: 'FMC',
        rating: 4.5,
        numReviews: 10,
        countInStock: 8,
        description: 'high quality product',
    },
    {
        name: 'Polytrin',
        category: 'Insecticides',
        image: '/images/product-5.jpg',
        price: 650,
        brand: 'SYNGENTA',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
        description: 'high quality product',
    },
    {
        name: 'Police',
        category: 'Insecticides',
        image: '/images/product-6.jpg',
        price: 600,
        brand: 'GHARHA',
        rating: 4.0,
        numReviews: 10,
        countInStock: 3,
        description: 'high quality product',
    },
  ],
};
export default data;
