export default {
    products: [
        {
            _id: '1',
            name: 'Coragen',
            category: 'Insecticides',
            image: '/images/product-1.jpg',
            price: 800,
            brand: 'FMC',
            rating: 4.0,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '2',
            name: 'Regent',
            category: 'Insecticides',
            image: '/images/product-2.jpg',
            price: 800,
            brand: 'BAYER',
            rating: 5.0,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Ampligo',
            category: 'Insecticides',
            image: '/images/product-3.jpg',
            price: 1600,
            brand: 'SYNGENTA',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Benevia',
            category: 'Insecticides',
            image: '/images/product-4.jpg',
            price: 1400,
            brand: 'FMC',
            rating: 4.5,
            numReviews: 10,
            countInStock: 8,
        },
        {
            _id: '5',
            name: 'Polytrin',
            category: 'Insecticides',
            image: '/images/product-5.jpg',
            price: 650,
            brand: 'SYNGENTA',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Police',
            category: 'Insecticides',
            image: '/images/product-6.jpg',
            price: 600,
            brand: 'GHARHA',
            rating: 4.0,
            numReviews: 10,
            countInStock: 3,
        },
    ],
};